Make the dirtydb fix backwards compatible.
AntelopeIO/DUNES pull request #225
Opened 2023-06-16 20:30 UTC by ScottBailey

2023-06-19 07:08 UTC, mikelik requested changes
I have following error:
```
mikel@msi:~/repo/DUNE$ ./dunes --start a00
Creating node [a00]
Using Configuration [/app/config.ini], which is copied to [/app/nodes/a00/config.ini]

start_node.sh: line 9: /app/$5.out: ambiguous redirect

ERROR: a00 is not running!
cat: /app/a00.out: No such file or directory
ERROR: docker ['container', 'exec', 'dunes_container', 'cat', '/app/a00.out']  -- returned: 1
Docker Error
mikel@msi:~/repo/DUNE$ ./dunes --version-all
DUNES v1.1.2
Listing... Done
leap/now 4.0.1 amd64 [installed,local]
Listing... Done
cdt/now 4.0.0-1 amd64 [installed,local]
reference-contracts AntelopeIO 76197b4bc60d8dc91a5d65ecdbf0f785e982e279
```

2023-06-20 15:25 UTC, ScottBailey commented
@mikelik Did you test with an existing DUNES image, bootstrap a new one, or use an old DUNE image?

If you used an existing DUNES image, it would fail like this.

2023-06-20 19:23 UTC, ScottBailey commented
@mikelik after further investigation, I am unable to recreate the error you had.

Does a full test work? i.e. `pytest --run-all tests/` 
Or, simpler: `pytest --run-all tests/test_nodes.py`

2023-06-21 07:56 UTC, mikelik commented
> @mikelik Did you test with an existing DUNES image, bootstrap a new one, or use an old DUNE image?
> 
> If you used an existing DUNES image, it would fail like this.

Yes, I have used old image from v1.1.0.
I misunderstood the requirements, I thought new scripts should work with old Docker image because of the description:
> This allows an older DUNE executable to call a newer DUNES container image and vice versa.

In that case, I'm fine with the change. Can you please update the description in the PR and in the issue?

2023-06-21 07:56 UTC, mikelik approved these changes

2023-06-21 14:43 UTC, merged